import { getProfiles } from "@/services/profile.service";
import {
  createTransaction,
  hasAutoSalaryTransaction,
} from "@/services/transaction.service";
import { getCategoryId } from "@/services/category.service";

let isCheckingAutoSalary = false;

function getTodayWIB() {
  const now = new Date();

  const formatter = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Jakarta",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });

  const [year, month, day] = formatter.format(now).split("-");

  return {
    year: Number(year),
    month: Number(month),
    day: Number(day),
    date: `${year}-${month}-${day}`,
  };
}

export async function checkAutoSalary(): Promise<void> {
  if (isCheckingAutoSalary) {
    return;
  }

  isCheckingAutoSalary = true;

  try {
    console.log("AUTO SALARY START");

    const today = getTodayWIB();

    const profiles = await getProfiles();

    for (const profile of profiles) {
      if (!profile.auto_salary_enabled) {
        continue;
      }

      if (!profile.salary_day) {
        continue;
      }

      if (!profile.base_salary) {
        continue;
      }

      if (profile.salary_day !== today.day) {
        continue;
      }

      const alreadyExists =
        await hasAutoSalaryTransaction(
          profile.id,
          today.year,
          today.month
        );

      if (alreadyExists) {
        continue;
      }

      const categoryId = await getCategoryId(
        "income",
        "Gaji Pokok"
      );

      await createTransaction({
        profileId: profile.id,
        categoryId,
        type: "income",
        amount: profile.base_salary,
        description: "Gaji Pokok",
        transactionDate: today.date,
        isAutoGenerated: true,
        source: "auto_salary",
      });
    }
  } finally {
    isCheckingAutoSalary = false;
  }
}