import { supabase } from "@/lib/supabase";

import { Profile } from "@/services/profile.service";

import { createTransaction } from "@/services/transaction.service";

import { getIncomeSalaryCategoryId } from "@/services/category.service";

import { getRecurringTransactionDate } from "@/utils/recurring";

export async function processAutoSalary(
  profile: Profile,
  today: Date
): Promise<void> {
  if (profile.salary <= 0) {
    return;
  }

  const year = today.getFullYear();
  const month = today.getMonth() + 1;

  const { data: existingLog, error: logCheckError } =
    await supabase
      .from("auto_salary_logs")
      .select("id")
      .eq("profile_id", profile.id)
      .eq("year", year)
      .eq("month", month)
      .maybeSingle();

  if (logCheckError) {
    throw logCheckError;
  }

  if (existingLog) {
    return;
  }

  const categoryId =
    await getIncomeSalaryCategoryId();

  const transactionDate =
    getRecurringTransactionDate(
      year,
      month,
      profile.payday
    );

  const transaction =
    await createTransaction({
      profileId: profile.id,

      categoryId,

      type: "income",

      amount: profile.salary,

      description: "Auto Salary",

      transactionDate,

      isAutoGenerated: true,

      source: "salary",
    });

  const { error: insertLogError } =
    await supabase
      .from("auto_salary_logs")
      .insert({
        profile_id: profile.id,

        transaction_id: transaction.id,

        year,

        month,

        status: "generated",
      });

  if (insertLogError) {
    throw insertLogError;
  }
}