import { supabase } from "@/lib/supabase";
import { validateTransactionTimeline } from "@/services/financial-timeline.service";

export interface TransactionPayload {
  profileId: string;
  categoryId: string;

  type: "income" | "expense";

  amount: number;

  description: string;

  transactionDate: string;

  isAutoGenerated?: boolean;

  source?: string;
}

export async function createTransaction(
  payload: TransactionPayload
) {
  // Validasi timeline transaksi
  await validateTransactionTimeline(
    payload.transactionDate
  );

  const [year, month] = payload.transactionDate
    .split("-")
    .map(Number);

  const { data, error } = await supabase
    .from("transactions")
    .insert({
      profile_id: payload.profileId,
      category_id: payload.categoryId,

      type: payload.type,

      amount: payload.amount,

      description: payload.description,

      transaction_date: payload.transactionDate,

      year,

      month,

      is_auto_generated:
        payload.isAutoGenerated ?? false,

      source:
        payload.source ?? "manual",
    })
    .select()
    .single();

  if (error) {
    console.error(error);
    throw error;
  }

  return data;
}

export async function getTransactions(
  year: number,
  month: number
) {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name,
        role
      ),
      transaction_categories (
        name,
        icon,
        color,
        type
      )
    `)
    .eq("year", year)
    .eq("month", month)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    });

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function getRecentTransactions(
  year: number,
  month: number
) {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name,
        role
      ),
      transaction_categories (
        name,
        icon,
        color,
        type
      )
    `)
    .eq("year", year)
    .eq("month", month)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    })
    .limit(5);

  if (error) throw error;

  return data ?? [];
}

export async function getAllTransactions() {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name,
        role
      ),
      transaction_categories (
        name,
        icon,
        color,
        type
      )
    `)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    });

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function deleteTransaction(
  id: string
) {
  const { error } = await supabase
    .from("transactions")
    .delete()
    .eq("id", id);

  if (error) {
    throw error;
  }
}