import { supabase } from "@/lib/supabase";
import { validateTransactionTimeline } from "@/services/financial-timeline.service";

const OPENING_BALANCE_DESCRIPTION = "Saldo Awal";

export interface TransactionPayload {
  profileId: string;
  categoryId: string;

  type: "income" | "expense";

  amount: number;

  description: string;

  transactionDate: string;

  isAutoGenerated?: boolean;

  source?: string;
}

export interface OpeningBalancePayload {
  profileId: string;
  amount: number;
  transactionDate: string;
  categoryId: string;
}

export async function createTransaction(
  payload: TransactionPayload
) {
  await validateTransactionTimeline(
    payload.transactionDate
  );

  const [year, month] = payload.transactionDate
    .split("-")
    .map(Number);

  const { data, error } = await supabase
    .from("transactions")
    .insert({
      profile_id: payload.profileId,
      category_id: payload.categoryId,
      type: payload.type,
      amount: payload.amount,
      description: payload.description,
      transaction_date: payload.transactionDate,
      year,
      month,
      is_auto_generated:
        payload.isAutoGenerated ?? false,
      source:
        payload.source ?? "manual",
    })
    .select()
    .single();

  if (error) {
    console.error(error);
    throw error;
  }

  return data;
}

export async function createOpeningBalanceTransaction(
  payload: OpeningBalancePayload
) {
  return createTransaction({
    profileId: payload.profileId,
    categoryId: payload.categoryId,
    type: "income",
    amount: payload.amount,
    description: OPENING_BALANCE_DESCRIPTION,
    transactionDate: payload.transactionDate,
    isAutoGenerated: true,
    source: "opening_balance",
  });
}

export async function getTransactions(
  year: number,
  month: number
) {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name
      ),
      transaction_categories (
        name,
        type
      )
    `)
    .eq("year", year)
    .eq("month", month)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    });

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function getRecentTransactions(
  year: number,
  month: number
) {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name
      ),
      transaction_categories (
        name,
        type
      )
    `)
    .eq("year", year)
    .eq("month", month)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    })
    .limit(5);

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function getAllTransactions() {
  const { data, error } = await supabase
    .from("transactions")
    .select(`
      *,
      profiles (
        name
      ),
      transaction_categories (
        name,
        type
      )
    `)
    .order("transaction_date", {
      ascending: false,
    })
    .order("created_at", {
      ascending: false,
    });

  if (error) {
    throw error;
  }

  return data ?? [];
}

export async function deleteTransaction(
  id: string
) {
  const { error } = await supabase
    .from("transactions")
    .delete()
    .eq("id", id);

  if (error) {
    throw error;
  }
}

export async function hasAutoSalaryTransaction(
  profileId: string,
  year: number,
  month: number
): Promise<boolean> {
  const { count, error } = await supabase
    .from("transactions")
    .select("id", {
      count: "exact",
      head: true,
    })
    .eq("profile_id", profileId)
    .eq("source", "auto_salary")
    .eq("year", year)
    .eq("month", month);

  if (error) {
    throw error;
  }

  return (count ?? 0) > 0;
}